GET http://localhost:3000

### get all books
GET http://localhost:3000/api/books

### get Single book
GET http://localhost:3000/api/books/Test

### del Single book
DELETE http://localhost:3000/api/books/Book%201

### Create book
POST http://localhost:3000/api/books
Content-Type:  application/json

{
    "title": "Book 8",
    "author": "Author 6",
    "isPublished": false,
    "year": "2027"
}